# Generated by Django 4.0.5 on 2022-06-20 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0002_alter_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celuar_contacto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='coreeo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
