# Generated by Django 4.0.5 on 2022-06-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0005_alter_persona_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'motivo',
                'verbose_name_plural': 'motivos',
            },
        ),
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('fecha_ausentismo', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('tiempo_ausentismo', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.persona')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.motivoausentismo')),
            ],
            options={
                'verbose_name': 'ausentismo',
                'verbose_name_plural': 'ausentismos',
            },
        ),
    ]
