# Generated by Django 4.0.5 on 2022-06-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0006_motivoausentismo_ausentismo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='celuar_contacto',
            new_name='celular_contacto',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='coreeo_contacto',
            new_name='correo_contacto',
        ),
    ]
