# Generated by Django 4.0.5 on 2022-07-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0007_rename_celuar_contacto_persona_celular_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('aplicacion', models.CharField(max_length=255)),
                ('extra_v', models.CharField(max_length=100)),
                ('capitulo', models.CharField(max_length=100)),
                ('usuario_responsable', models.CharField(max_length=200)),
                ('publico_privado', models.CharField(choices=[('Pri', 'Privada'), ('Pub', 'Publica')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CIE 10',
                'verbose_name_plural': 'CIE 10',
            },
        ),
        migrations.CreateModel(
            name='Csst_ba_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condición Básica Laborel',
                'verbose_name_plural': 'Condiciones Básicas Laborales',
            },
        ),
        migrations.CreateModel(
            name='Csst_ba_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condición Básica Personal',
                'verbose_name_plural': 'Condiciones Básicas Personales',
            },
        ),
        migrations.CreateModel(
            name='Csst_inm_amb_subestandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condición Inmediata Ambiental Subestandar',
                'verbose_name_plural': 'Condiciones Inmediatas Ambientales Subestandar',
            },
        ),
        migrations.CreateModel(
            name='Csst_inm_subestandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condición Inmediata Subestandar',
                'verbose_name_plural': 'Condiciones Inmediatas Subestandar',
            },
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accidente', models.DateField()),
                ('hora_accidente', models.TimeField()),
                ('tipo_jornada', models.CharField(choices=[('O', 'ORDINARIA'), ('A', 'ADICIONAL'), ('T', 'TURNOS')], max_length=1)),
                ('inicio_jornada', models.TimeField()),
                ('final_jornada', models.TimeField()),
                ('fallecido', models.BooleanField(default=False)),
                ('incapacidad', models.BooleanField(default=False)),
                ('invalidez', models.BooleanField(default=False)),
                ('dias_incapacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('grado_invalidez', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion_accidente', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('acto_subestandar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.csst_inm_subestandar')),
                ('codigo_cie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.cie10')),
                ('cond_ambientales_subestandar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.csst_inm_amb_subestandar')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.persona')),
                ('factor_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.csst_ba_laboral')),
                ('factor_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.csst_ba_personal')),
            ],
            options={
                'verbose_name': 'accidente',
                'verbose_name_plural': 'accidentes',
            },
        ),
    ]
