# Generated by Django 4.0.5 on 2022-07-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0008_cie10_csst_ba_laboral_csst_ba_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cie10',
            name='aplica_sexo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cie10',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cie10',
            name='edad_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='edad_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='estandar_gel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cie10',
            name='estandar_msps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cie10',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cie10',
            name='grupo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='grupo_mortalidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cie10',
            name='subcategoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='subgrupo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cie10',
            name='valor_registro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
