# Generated by Django 4.0.5 on 2022-07-11 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0010_alter_cie10_aplica_sexo_alter_cie10_aplicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosAccInsumosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Costos Accidente Insumo Médico',
                'verbose_name_plural': 'Costos Accidnte Insumos Médicos',
            },
        ),
    ]
