# Generated by Django 4.0.5 on 2022-07-12 18:15

import ausentismoApp.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0012_alter_accidente_fallecido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidente',
            name='fecha_accidente',
            field=models.DateField(validators=[ausentismoApp.validators.validador_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='costosaccinsumosmedicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='CostosAccTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Costo de transporte',
                'verbose_name_plural': 'Costos de transporte',
            },
        ),
    ]
