# Generated by Django 4.0.5 on 2022-07-13 03:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0013_alter_accidente_fecha_accidente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costosacctransporte',
            old_name='insumo',
            new_name='elemento',
        ),
        migrations.CreateModel(
            name='CostosAccOtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Otro costo',
                'verbose_name_plural': 'Otros costos',
            },
        ),
    ]
