# Generated by Django 4.0.5 on 2022-07-17 04:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0014_rename_insumo_costosacctransporte_elemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosAccRepuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Repuesto requerido',
                'verbose_name_plural': 'Lista de repuestos requeridos',
            },
        ),
        migrations.CreateModel(
            name='CostosAccMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Maquinaria requerida',
                'verbose_name_plural': 'Lista de maquinaria requerida',
            },
        ),
        migrations.CreateModel(
            name='CostosAccManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Mano de obra requerida',
                'verbose_name_plural': 'Lista de mano de obra requerida',
            },
        ),
    ]
