# Generated by Django 3.2.14 on 2022-07-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0017_expectativavida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectativavida',
            name='expectativa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
