# Generated by Django 3.2.14 on 2022-07-18 02:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0018_alter_expectativavida_expectativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosAccDanoEmergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
            ],
            options={
                'verbose_name': 'Daño emergente',
                'verbose_name_plural': 'Lista de daños emergentes',
            },
        ),
    ]
