# Generated by Django 3.2.14 on 2022-07-19 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0019_costosaccdanoemergente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorTiemposAcompanamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acompanamiento', models.CharField(max_length=5, unique=True)),
                ('descripción', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factor tiempo acompañamiento',
                'verbose_name_plural': 'Lista de factores',
            },
        ),
        migrations.CreateModel(
            name='TiemposAccAcompanamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acompanamiento', models.CharField(choices=[('A', 'Se encontraba en la actividad con el accidentado al momento del accidente'), ('B', 'Ayudó en el rescate o estabilización del accidentado'), ('C', 'Se encontraba en el área del accidente'), ('D', 'Ayuda en la investigación del accidente'), ('E', 'Ayuda en la implementación de acciones de corrección')], max_length=1)),
                ('tiempo', models.TimeField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.accidente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.persona')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.factortiemposacompanamiento')),
            ],
            options={
                'verbose_name': 'Acompañaieno en el accidente',
                'verbose_name_plural': 'Acompañamientos en el accidente',
            },
        ),
    ]
