# Generated by Django 3.2.14 on 2022-07-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0020_factortiemposacompanamiento_tiemposaccacompanamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcompanamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo acompañamiento',
                'verbose_name_plural': 'Lista de tipos de acompañamiento',
            },
        ),
        migrations.AlterField(
            model_name='tiemposaccacompanamiento',
            name='tipo_acompanamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.tipoacompanamiento'),
        ),
    ]
