# Generated by Django 3.2.14 on 2022-07-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0021_auto_20220719_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorAccParafiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factor de accidentalidad por Parafiscales',
                'verbose_name_plural': 'Factores de accidentalidad por parafiscales',
            },
        ),
    ]
