# Generated by Django 3.2.14 on 2022-07-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0023_capacitadoraccidente_costosaccadicionales_reemplazoaccidente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacitadoraccidente',
            old_name='empleado',
            new_name='capacitador',
        ),
        migrations.RenameField(
            model_name='reemplazoaccidente',
            old_name='empleado',
            new_name='reemplazo',
        ),
    ]
