# Generated by Django 3.2.14 on 2022-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0024_auto_20220720_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
