# Generated by Django 3.2.14 on 2022-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0025_accidente_fecha_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='lucro_consolidado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='accidente',
            name='lucro_futuro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
