# Generated by Django 3.2.14 on 2022-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0029_nivdanomoral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parámetro de la aplicación',
                'verbose_name_plural': 'Lista de parametros',
            },
        ),
    ]
