# Generated by Django 3.2.14 on 2022-08-04 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0031_auto_20220803_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='tiempo_ausentismo',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
