# Generated by Django 3.2.14 on 2022-08-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0032_ausentismo_tiempo_ausentismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='periodo_ausentismo',
            field=models.CharField(choices=[('D', 'Día'), ('H', 'Hora')], max_length=2),
        ),
    ]
