# Generated by Django 3.2.14 on 2022-08-04 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0033_alter_ausentismo_periodo_ausentismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='tiempo_ausentismo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
