# Generated by Django 3.2.14 on 2022-08-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0037_auto_20220807_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='reemplazoaccidente',
            name='nombre_reemplazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capacitadoraccidente',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reemplazoaccidente',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ausentismoApp.persona'),
        ),
    ]
