# Generated by Django 3.2.14 on 2022-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0038_auto_20220813_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reemplazoaccidente',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
