# Generated by Django 3.2.14 on 2022-08-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0040_alter_reemplazoaccidente_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reemplazoaccidente',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ausentismoApp.persona'),
        ),
    ]
