# Generated by Django 3.2.14 on 2022-08-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0041_alter_reemplazoaccidente_reemplazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reemplazoaccidente',
            name='valor_salarial_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
