# Generated by Django 3.2.14 on 2022-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismoApp', '0042_reemplazoaccidente_valor_salarial_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoraccparafiscales',
            name='factor',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
