# Generated by Django 3.2.14 on 2023-03-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ausentismoApp", "0043_alter_factoraccparafiscales_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceAccidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo1",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo2",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo3",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo4",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo5",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo6",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo7",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo8",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo9",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo10",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo11",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo12",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo13",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo14",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo15",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo16",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo17",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo18",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo19",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo20",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo21",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo22",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo23",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo24",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("AI", "AI"),
                            ("ND", "ND"),
                            ("NI", "NI"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "accidente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ausentismoApp.accidente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance clasificado por tipologia",
                "verbose_name_plural": "Balances clasificados por tipologia",
            },
        ),
    ]
